# Dockerfile-nginx

FROM nginx:latest

# Nginx listens on http port 5000

EXPOSE 5000

# Remove the Nginx default config fso it doesn't clobber our settings

RUN rm /etc/nginx/conf.d/default.conf

# Copy over our required config for uwsgi reverse proxy

COPY app.conf /etc/nginx/conf.d
