version: "3"
services:
  flask:
    image: flask-uwsgi-app
    build:
      context: .
      dockerfile: Dockerfile-flask
    volumes:
      - "./:/app"
  nginx:
    image: nginx-uwsgi-proxy
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 5000:5000
    depends_on:
      - flask
